services:
  # Nginx reverse proxy
  nginx-proxy:
    build: ./proxy
    container_name: main-proxy
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
    networks:
      - proxy-network
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "wget", "--quiet", "--tries=1", "--spider", "http://localhost/"]
      interval: 30s
      timeout: 10s
      retries: 3

  # DNS server
  dnsmasq:
    build: ./dns
    container_name: dnsmasq-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns-network
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  proxy-network:
    name: proxy-network
  dns-network:
    name: dns-network