version: '3.8'

services:
  dnsmasq:
    build: .
    container_name: dnsmasq-server
    ports:
      - "53:53/udp"
      - "53:53/tcp"
    networks:
      - dns-network
    restart: unless-stopped
    cap_add:
      - NET_ADMIN
    healthcheck:
      test: ["CMD", "nslookup", "google.com", "localhost"]
      interval: 30s
      timeout: 10s
      retries: 3

networks:
  dns-network:
    name: dns-network
    external: true