name: Deploy Proxy

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Deploy Nginx Proxy
    runs-on: self-hosted

    env:
      DOCKER_HOST: tcp://10.0.0.35:2375

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Deploy
        run: |
          docker compose down || true
          docker compose up -d

      - name: Verify
        run: |
          sleep 5
          docker ps | grep main-proxy
          docker ps | grep dnsmasq-server
          docker logs main-proxy --tail 20
          docker logs dnsmasq-server --tail 20